name: Run Parasoft C++ Analysis

on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**.cxx'
      - '**.hpp'
      - '**.cc'
      - '**.hh'
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-parasoft-analysis:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Unique Build ID
        run: echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV

      - name: Run Parasoft C++test in Docker
        run: |
          docker exec cpp_project cpptestcli \
            -config "builtin://SEI CERT C Rules" \
            -compiler gcc_10-64 \
            -property build.id="${dtp_project}-build_id_1" \
            -publish -- /usr/bin/gcc -c /home/parasoft/workspace_BIU_TEST/sensor_c/sensor_c.c -o /home/parasoft/workspace_BIU_TEST/sensor_c/sensor_c.o
