name: Run Parasoft C++ Analysis

on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**.cxx'
      - '**.hpp'
      - '**.cc'
      - '**.hh'
  workflow_dispatch: # Enables manual trigger from GitHub UI

jobs:
  run-parasoft-analysis:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Unique Build ID
        run: echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV

      - name: Debug Docker Mounts
        run: docker inspect cpp_project # Checks if workspace is correctly mounted

      - name: Run Parasoft C++ Analysis in Docker
        run: |
          docker exec -w /home/parasoft/workspace_BIU_TEST/sensor_c cpp_project \
          cpptestcli -config "builtin://SEI CERT C Rules" \
          -compiler gcc_10-64 \
          -property build.id="cpp_project_build_${{ env.BUILD_ID }}" \
          -publish -- /usr/bin/gcc -c sensor_c.c -o sensor_c.o
